### ISSUE TITLE
langpackage - JSON parsing error

### ISSUE THREAD

**Issue by bitcoinvsalts** [sungmaster/langPackage#1]
I am getting this error:

```
langpackage - JSON parsing error
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Lang.importJSON (/Users/herve76/Desktop/chatbot/node_modules/langpackage/index.js:65:22)
    at Object.<anonymous> (/Users/herve76/Desktop/chatbot/app/index.js:39:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/herve76/Desktop/chatbot/server.js:1:79)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

```

using this code:

```
const EN_file = require('./locales/en')
let langPack = {}
langPack.en = new langPackage()
langPack.en.importJSON(EN_file)

```

And here is the content of en.json:

```
{
	"hello":["Hello"],
	"hi":["Hi"]
}
```

**Comment by bitcoinvsalts** [comment]
I fixed it using:

langPack.en.importJSON(JSON.stringify(EN_file))
